# Nombre del servicio
spring.application.name=ms-usuarios

# Puerto
server.port=8083

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:postgresql://postgres:uIciXTZVbgKaLgOtzyBBEfmbuyAExdbT@postgres.railway.internal:5432/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:uIciXTZVbgKaLgOtzyBBEfmbuyAExdbT}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Desactiva open-in-view
spring.jpa.open-controllerin-view=false

logging.level.org.springframework.web=DEBUG